Add getters for output & input device number
Mikatux/voicemeeter-remote pull request #10
Opened 2023-09-10 09:13 UTC by Raraph84

All is in the title ^^

2023-10-23 08:57 UTC, Raraph84 commented
@Mikatux ?

2023-10-25 14:05 UTC, Mikatux requested changes

2023-10-25 14:06 UTC, Raraph84 commented on package.json
> +  "version": "0.3.1",
It's because I already published 0.3.0 via a tag and I forgot to push the version update

2023-10-25 14:08 UTC, Mikatux approved these changes

2023-10-25 14:08 UTC, Mikatux commented on package.json
> +  "version": "0.3.1",
Ok you right got for it then

2023-10-25 14:08 UTC, merged